# Site settings
title: 솔라빔
description: "Yet Another Minimal Theme"
url: "https://libkim.github.io"
baseurl: "/"
author:
  name: "libkim"
  email: "libkimh@gmail.com"
  url: "https://libkim.github.io"
permalink: /:year/:month/:day/:title:output_ext

#Plugins
plugins: [jekyll-paginate, jekyll-feed, jekyll-seo-tag, jekyll-sitemap]

#Pagination
paginate: 3
paginate_path: "/page:num/"

#SEO
twitter:
  username:
  card:
facebook:
  app_id:
  publisher:
  admins:
logo: /assets/img/logo.jpg
social:
  links: #List your social links here
    - https://www.pixiv.net/users/62783858
    - https://www.github.com/pandasekh
    - https://www.linkedin.com/in/alessio-franceschi/
webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
  baidu:
lang: en_US

#Highlighter
kramdown:
  input:          GFM
  syntax_highlighter: rouge

  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

#Sass
sass:
  style: compressed
  sourcemap: never
