#Site settings
title: '金 立'
description: '엎질러진글들의도서관'
url: 'https://libkim.github.io/'
baseurl:
permalink: '/:year/:month/:day/:title'

#Manifest
manifest_name: 'Web App Full Name'
manifest_short_name: 'Short Name' # Appears in "Add to home screen" dialogues and may have other importance also
manifest_lang: en
manifest_background_color: white
manifest_short_name:
manifest_display: standalone

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 3
paginate_path: '/page:num/'

# SEO
twitter:
  username:
  card:
facebook:
  app_id:
  publisher:
  admins:
logo: /assets/img/logo.jpg
social:
  links:
    - 'https://github.com/pandasekh'
    - 'https://linkedin.com/in/alessio-franceschi/'
webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
  baidu:
lang: en_US

# Highlighter
kramdown:
  input: GFM
  syntax_highlighter: rouge

  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

# Sass
sass:
  style: compressed
  sourcemap: never