#Site settings
title: 金立圖書館
en-title: Lib Kim Library
description: Welcome to Lib Kim Library.
url: 'https://libkim.github.io/'
permalink: '/:title'

collections:
  my_posts:
    output: true
    permalink: '/posts/:title:output_ext'

defaults:
  - scope:
      path: ''
      type: my_posts
    values:
      layout: post
  - scope:
      path: ''
      type: projects
    values:
      layout: project

#Manifest
manifest_name: 金Lib. — Lib Kim Library
manifest_short_name: 金Lib.
manifest_lang: en
manifest_background_color: white
manifest_display: standalone

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - webrick

# SEO
twitter:
  username:
  card:
facebook:
  app_id:
  publisher:
  admins:
logo: /assets/img/logo.jpg
social:
  links:
    - 'https://github.com/pandasekh'
    - 'https://linkedin.com/in/alessio-franceschi/'
webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
  baidu:
lang: en_US

# Highlighter
kramdown:
  input: GFM
  syntax_highlighter: rouge

  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

# Sass
sass:
  style: compressed
  sourcemap: never


