#Subtitle
subtitle:
  active: true
  text: 엎질러진글들의도서관

#Featured images in homepage
featured-img:
  active: true

#Show categories at the end of posts
categories:
  active: true

#Use MathJAX
mathjax:
  active: true

#Show related posts based on categories
related-posts:
  active: true
  title: 'You May Also Enjoy'

#Comments
comments: true
