name: Ani List Scraper

on:
  schedule:
    - cron: '0 17 * * 1'
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run Scraper with python
        run: |
          python "scraper.py"
          
      - name: Commits
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "libkimh@gmail.com"
          git add ani-list.yml
          git commit -m "Update ani-list.yml"
          
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          branch: 'master'
          github_token: $
